% Run the test cases from the riscv-tests suite
% https://github.com/riscv-software-src/riscv-tests

classdef RunRiscvTests < matlab.unittest.TestCase

    properties (MethodSetupParameter)
        TVMName = {"rv32ui"}
        targetEnvironment = {"p"}
        testName =  {   "add", ...
                        "addi", ...
                        "and", ...
                        "andi", ...
                        "auipc", ...
                        "beq", ...
                        "bge", ...
                        "bgeu", ...
                        "blt", ...
                        "bltu", ...
                        "bne", ...
                        "jal", ...
                        "jalr", ...
                        "lb", ...
                        "lbu", ...
                        "ld_st", ...
                        "lh", ...
                        "lhu", ...
                        "lui", ...
                        "lw", ...
                        "ma_data", ...
                        "or", ...
                        "ori", ...
                        "sb", ...
                        "sh", ...
                        "simple", ...
                        "sll", ...
                        "slli", ...
                        "slt", ...
                        "slti", ...
                        "sltiu", ...
                        "sltu", ...
                        "sra", ...
                        "srai", ...
                        "srl", ...
                        "srli", ...
                        "st_ld", ...
                        "sub", ...
                        "sw", ...
                        "xor", ...
                        "xori", ...
                    };
    end

    properties
        elfFilePath;
    end

    methods (TestClassSetup)
        function printCommitHash(testCase)
            [~, hash] = system('git rev-parse HEAD');
            disp("Commit hash: "+string(strip(hash)));
        end
    end

    methods (TestMethodSetup)
        function getFilePath(testCase, TVMName, targetEnvironment, testName)
            testFolderPath = strcat(SimuRISC_Environment.RISCV_TESTS_PATH, filesep, "isa");
            testCase.elfFilePath = testFolderPath+filesep+TVMName+"-"+targetEnvironment+"-"+testName;
            
        end
    end

    methods (Test)
        function testExecution(testCase)

            % Run test on model
            modelOutput = runTestCase("ElfFilePath", testCase.elfFilePath, ...
                "StartSection","test_2", ...
                "StopCondition", "ecall");
        
            % Check results
            % x17 is 93 for syscall exit
            testCase.verifyEqual(modelOutput.registerFile(18), uint32(93))
            % x11 is the return code
            testCase.verifyEqual(modelOutput.registerFile(11), uint32(0))
        end
    end
end